---
title: "Using `flex_bib`"

author:
  - Paul C. Bauer^[University of Mannheim, paul.bauer@mzes.uni-mannheim.de]
  - Denis Cohen^[University of Mannheim, denis.cohen@mzes.uni-mannheim.de]
date: "`r Sys.Date()`"


fontsize: 11pt
linestretch: 1

output:
  bookdown::pdf_document2:
    fig_caption: yes
    number_sections: no
    toc: false
    pandoc_args: --lua-filter=multiple-bibliographies.lua
    keep_tex: no

header-includes:
  - \usepackage {hyperref}
  - \hypersetup {colorlinks = true, linkcolor = blue, urlcolor = blue}

bibliography_main:
  - partial_bib_1.bib
bibliography_app:
  - partial_bib_2.bib
link-citations: yes
linkcolor: blue
---
  
```{r setup, include=FALSE}
## ---- Setup ----
## Save package names as a vector of strings
pkgs <-
  c("rmarkdown",
    "stringr",
    "bib2df",
    "dplyr",
    "devtools")

## Install uninstalled packages
lapply(pkgs[!(pkgs %in% installed.packages())], install.packages)

## Load all packages to library and adjust options
lapply(pkgs, library, character.only = TRUE)

## Set display options
options(scipen=999)
```

```{r tidy-bib, include=FALSE}
source_url("https://raw.githubusercontent.com/paulcbauer/flex_bib/master/flex_bib.R")
flex_bib(
  rmarkdown_file = "manuscript.Rmd",
  bib_input = c("references1.bib", "references2.bib"),
  bib_output = "partial_bib.bib",
  by_sections = c("<!--- flex_bib appendix split -->"),
  repair = TRUE,
  removeISSN = TRUE,
  removeISBN = TRUE,
  removeDOI = TRUE,
  removeURL = TRUE
)
```

## Main Text

This is the main text. It cites one paper by @Athey2019-fy inline.
We also cite a book by @Berelsonetal1954. 

Let's also cite a report in parantheses [@Gallup2019].
Here is also some more intricate stuff with prefixes and suffixes
[e.g., @Hargittai2008-fa, pp. 31-57].

## Main Text References
<div id="refs_main"></div>

<!--- flex_bib appendix split -->
## Appendix

This is the appendix. It cites some other paper [@Friedman2009-gx].

## Appendix References
<div id="refs_app"></div>
